### PR TITLE
(Bug Fix) : First occurence of text changes on deleting input value from last

### PR DESCRIPTION
**Pull request by shubhamV123**
Fixed  issue when deleting the last keyword from the input it deletes the first occurrence of the keyword

### CODE REVIEW

**Comment by msudgh** [comment]
Resolved #9

**Comment by msudgh** [comment]
@DivyanshBatham @shubhamV123 Thanks. named as release v1.2.4

**Comment by shubhamV123** [comment]
@msudgh Example is not updated and so do the package. I think you need to trigger update of the package as well. I am getting the older source code.

**Comment by msudgh** [comment]
@shubhamV123 Yes, I know didn't release it yet. I'm setting up some linting tools.

**Pull request merged**
